version: "3.8"

services:
    seoulair-dashboard:
        container_name: seoulair-dashboard
        image: seoulair-dashboard
        restart: always
        build:
            context: ./
            dockerfile: Dockerfile
        network_mode: bridge
        ports:
            - 8080:80
        external_links:
            - seoulair-gateway